### PR TITLE
ENH: Propose metabolite cycling dim definition.

### PR DESCRIPTION
**Pull request by wtclarke**
Add `DIM_METCYCLE` to the dimensions definitions for storing metabolite cycled data .

@schorschinho, @HJZollner, @markmikkelsen, @martin3141 any comments on the naming or requests for additional information to go with this tag?

### CODE REVIEW

**Comment by markmikkelsen** [comment]
Hi @wtclarke,

Sounds good to me! My only thought regarding the `DIM_ISIS` tag is that it could apply to other multi-step experiments like [MEGA-SPECIAL](https://doi.org/10.1002/nbm.1688).

Mark

**Comment by schorschinho** [comment]
No complaints about `DIM_METCYCLE`. I'll pull the specifications file over into Osprey once you've merged it here. 

> Hi @wtclarke,
> 
> Sounds good to me! My only though regarding the `DIM_ISIS` tag is that it could apply to other multi-step experiments like [MEGA-SPECIAL](https://doi.org/10.1002/nbm.1688).
> 
> Mark

`DIM_ISIS` isn't new though? I'd assume that a MEGA-SPECIAL dataset will use `DIM_ISIS` and `DIM_EDIT`.

**Comment by markmikkelsen** [comment]
Oh, my mistake. I didn't pay attention clearly enough to the file changes.

**Comment by martin3141** [comment]
Yup, all good from my perspective.

**Comment by wtclarke** [comment]
Thanks all.

**Comment by schorschinho** [comment]
Now also in Osprey https://github.com/schorschinho/osprey/commit/77f45e61f74197a4ba5777bb75cc16aac93d5423

**Pull request merged**
